### ISSUE TITLE
some mistakes when I downloading it  

### ISSUE THREAD

**Issue by alvinwongcsh** [itlabers/ofd-go#1]
When I run "go get -d github.com/itlabers/ofd-go"
I got this error: "module declares its path as: ofd but was required as: github.com/itlabers/ofd-go"

Thanks for your job about OFD . It seems the first Go version for OFD standard .

**Comment by itlabers** [comment]
Thank you for your feedback.

Golang  module  name  has been modified,you can try again.

**Comment by alvinwongcsh** [comment]
it works now . thanks.
